management:
  endpoints:
    web:
      exposure:
        include: "*"


     
trainer:
  location: Gurgaon     
---
spring:
  profiles: dev

trainer:
  location: Pune
    
---
spring:
  profiles: test

trainer:
  location: Kolkata
---
spring:
  profiles:
    active: dev  
         
             