management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8601/eureka
     
trainer:
  location: Gurgaon     
---
spring:
  profiles: dev

trainer:
  location: Pune
    
---
spring:
  profiles: test

trainer:
  location: Kolkata
---
spring:
  profiles:
    active: dev  
         
             